spec: {{ specUrl }}
namespace: ApiClients\Client\{{ namespace }}
destination:
  root: ../
  source: clients
schemas:
  allowDuplication: true
  useAliasesForDuplication: true
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
subSplit:
  templatesDir: ../templates
  branch: {{ branch }}
  subSplitConfiguration: etc/config.subsplit-publish.json
  fullName: {{ fullName }} {{ "{{ section }}" }}
  vendor: api-clients
  sectionGenerator:
    - ApiClients\Tools\OpenApiClientGenerator\SectionGenerator\OperationIdSlash
    - ApiClients\Tools\OpenApiClientGenerator\SectionGenerator\WebHooks
  rootPackage:
    name: {{ packageName }}
    repository: git@github.com:php-api-clients/github.git
  sectionPackage:
    name: {{ packageName }}-{{ "{{ section }}" }}
    repository: git@github.com:php-api-clients/github-{{ "{{ section }}" }}.git
